# -*- coding: utf-8 -*-
"""meu_primeiro_codigo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HY4J6zVLvJQIBPRCKUkQycZokpTMRTyI
"""

import matplotlib.pyplot as plt

#grafico linha
#variaveis
x = [1, 2, 3, 4, 5]
y = [2, 3, 7, 1, 5]
#grafico barras
#variaveis
titulo = "GRAFICO de BARRAS"
eixoX = "EIXO X"
eixoY = "EIXO Y"

#título
plt.title ("MEU PRIMEIRO GRAFICO COM PYTHON")

#eixos
plt.xlabel("EIXO X")
plt.ylabel("EIXO Y")

#plotar o grafico
plt.plot(x, y)

#imprimir grafico
plt.show()

#grafico barras
#variaveis
titulo = "GRAFICO de BARRAS"
eixoX = "EIXO X"
eixoY = "EIXO Y"

#legendas
plt.title (titulo)
plt.xlabel(eixoX)
plt.ylabel(eixoY)

#plotar o grafico
plt.bar (x, y)

#grafico pontos

#variaveis
x = [1, 2, 3, 4, 5]
y = [2, 3, 7, 1, 5]

#variaveis
titulo = "GRAFICO de BARRAS"
eixoX = "EIXO X"
eixoY = "EIXO Y"

#legendas
plt.title (titulo)
plt.xlabel(eixoX)
plt.ylabel(eixoY)

#plotar o grafico
plt.plot (x, y,label="linha q liga os pontos locos", color="r") #grafico de linhas para ligar os pontos
plt.scatter (x, y, label="os pontos locos", color="black")#color pra mudar a cor
plt.legend()
#imprimir grafico
plt.show()

# https://matplotlib.org/api/_as_gen/matplotlib.pyplot.plot.html documentaçao pra alterar os pontos, linhas e cores

#grafico barras
#variaveis
titulo = "GRAFICO de BARRAS"
eixoX = "EIXO X"
eixoY = "EIXO Y"

#legendas
plt.title (titulo)
plt.xlabel(eixoX)
plt.ylabel(eixoY)

#plotar o grafico de barras
plt.bar (x, y)

#imprimir grafico
plt.show()

#comparando graficos
#variaveis
x1 = [1, 3, 5, 7, 9]
y1 = [2, 3, 7, 1, 5]

x2 = [2, 4, 6, 8, 10]
y2 = [5, 1, 3, 7, 4]
#grafico barras
#variaveis
titulo = "GRAFICO de BARRAS"
eixoX = "EIXO X"
eixoY = "EIXO Y"


#legendas
plt.title (titulo)
plt.xlabel(eixoX)
plt.ylabel(eixoY)

#plotar o grafico
plt.bar (x1, y1, label = "grupo 1")
plt.bar (x2, y2, label = "grupo 2")
plt.legend()#imprimi as label

#imprimir grafico
#plt.show()
plt.savefig("figura1.png")#salva o grafico em PNG

